### ISSUE TITLE
thinkphp5.1 崩溃

### ISSUE THREAD

**Issue by sofwu** [hooklife/thinkphp5-wechat#14]
[4096] ErrorException in Collection.php line 48
Argument 1 passed to EasyWeChat\Support\Collection::__construct() must be of the type array, null given, called in

**Comment by hooklife** [comment]
看下这个文件是否存在application/extra/wechat.ph

**Comment by sofwu** [comment]
升级到thinkphp5.1好多都不兼容，我在慢慢调试中
