### ISSUE TITLE
怎么增加本地授权调试呢？

### ISSUE THREAD

**Issue by ZhuoWei93** [hooklife/thinkphp5-wechat#4]
在laravel 中就有本地调试授权，不封装集成进去吗？？还是现在不维护了？

**Comment by hooklife** [comment]
Laravel 是在中间件中实现的这个功能，TP实现起来可能比较麻烦我会想想办法尽量在下一个版本中增加，最近会进行一次更新的~

**Comment by ZhuoWei93** [comment]
非常感谢
