### ISSUE TITLE
关于 application\extra目录下文件的问题

### ISSUE THREAD

**Issue by rcj654020445** [hooklife/thinkphp5-wechat#5]
你好，application\extra这个目录下需要wechat.php文件吗？

**Comment by hooklife** [comment]
不需要  只要composer下载下来之后执行这个命令php think wechat:config 就会自动生成wechat.php这个文件，然后修改其中的参数就好了。


如果不想执行命令可以手动下载这个文件  https://raw.githubusercontent.com/hooklife/thinkphp5-wechat/master/src/config.php 放入 application\extra 并更名为 wechat.php

**Comment by rcj654020445** [comment]
好的，谢谢啦
