### ISSUE TITLE
服务端验证

### ISSUE THREAD

**Issue by rcj654020445** [hooklife/thinkphp5-wechat#6]
我用tp5写了一个方法，我把微信服务端验证的地址填写为我写的这个方法，这个方法里该写些啥？有例子可参考吗？

**Comment by hooklife** [comment]
我不太清楚的问题具体是什么，我理解的是网页授权的回调方法应该写什么
你可以参考一下这个
https://easywechat.org/zh-cn/docs/oauth.html

还有有问题可以附上代码，和详细问题。
