### ISSUE TITLE
如何替换缓存引擎

### ISSUE THREAD

**Issue by Liangkk** [hooklife/thinkphp5-wechat#7]
请问楼主,按照官网文档形式替换缓存引擎
public static function app()
    {
        if (!isset(self::$app)) {
            $options = Config::get('wechat');
            $cacheDriver =new RedisCache();
            $redis=new think\cache\driver\Redis();
            $cacheDriver->setRedis($redis->handler());
            $options['cache']=$cacheDriver;
            self::$app = new Application($options);
        }
        return self::$app;
    }
但是发现,在调用获取用户信息接口后,缓存数据库还是为空,是否证明缓存驱动替换失败呢?

**Comment by hooklife** [comment]
获取用户信息和缓存有什么关系？具体说说你需要的功能。
